# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven + JaCoCo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  autotests:
    name: Run tests and generate JaCoCo Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Install dependencies
        run: mvn dependency:go-offline compile compiler:testCompile

      - name: Run Test
        if: always()
        run: mvn clean test
        continue-on-error: true
        
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5
        with:
          reports: 'target/my-reports/jacoco.xml'
          targetdir: 'target/coverage'
          reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
          assemblyfilters: '-xunit*'
      
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
#           PUBLISH_DIR: 'target/coverage'
          PUBLISH_DIR: 'target/my-reports'
          
